#!/usr/bin/env python3

from http.server import HTTPServer, BaseHTTPRequestHandler

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(302)
        self.send_header('Location', "https://hackathon.cambridgecryptographic.com")
        self.end_headers()


server = HTTPServer(('0.0.0.0', 80), Handler)
server.serve_forever()