require_relative '../node_modules/react-native/scripts/react_native_pods'
# Override Firebase SDK Version
$FirebaseSDKVersion = '6.29.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 
platform :ios, '12.0'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
target 'lovecrypto' do
  # Pods for lovecrypto
  
  config = use_native_modules!

  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => true
  )


  target 'lovecryptoTests' do
    inherit! :complete
    # Pods for testing
  end

  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end 
  end
end

##target 'lovecrypto-tvOS' do
  # Pods for lovecrypto-tvOS

 ## target 'lovecrypto-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
 # end
#end
 
