
//CLICK
export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
export const CLICK_OTHER_UPDATE_VALUE = 'CLICK_OTHER_UPDATE_VALUE';

//AUTH
export const SET_REFERAL_CODE = "SET_REFERAL_CODE";
export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const CHECK_USER_SESSION = "CHECK_USER_SESSION";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_OUT_START = "SIGN_OUT_START";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SET_FIRST_ACCESS = "SET_FIRST_ACCESS";
export const SET_PIN = "SET_PIN"; 
 
//USER
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const UPDATE_USER_CPF = "UPDATE_USER_CPF";
export const UPDATE_USER_PHONE = "UPDATE_USER_PHONE";
export const ADD_USER_BALANCE = "ADD_USER_BALANCE";
export const SET_WALLETS = "SET_WALLETS";
export const ADD_USER_POINTS = "ADD_USER_POINTS";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";
export const SET_USER_PHOTO = "SET_USER_PHOTO";
export const SET_PHONE_VERIFIED = "SET_PHONE_VERIFIED";
export const SET_EMAIL_VERIFIED = "SET_EMAIL_VERIFIED"; 
export const SET_DOCUMENTS_VERIFIED = "SET_DOCUMENTS_VERIFIED"; 
export const SET_USER_GENDER = "SET_USER_GENDER";

 
//CONFIG
export const SET_APP_NOTIFICATIONS = "SET_APP_NOTIFICATIONS";
export const SET_EMAIL_NOTIFICATIONS = "SET_EMAIL_NOTIFICATIONS";
export const SET_DARK_MODE = "SET_DARK_MODE";
export const SET_CURRENCY = "SET_CURRENCY";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_BRL_VALUE = "SET_BRL_VALUE";
export const SET_SALDO_VISIVEL = "SET_SALDO_VISIVEL";

//WITHDRAW
export const SET_CURRENCY_TYPE = "SET_CURRENCY_TYPE";
export const SET_CRYPTO_WALLET = "SET_CRYPTO_WALLET";
export const SET_FIAT_WALLET = "SET_FIAT_WALLET";

export const SET_PIX_WALLET_PHONE = "SET_PIX_WALLET_PHONE";
export const SET_PIX_WALLET_EMAIL = "SET_PIX_WALLET_EMAIL";
export const SET_PIX_WALLET_CPF_CNPJ = "SET_PIX_WALLET_CPF_CNPJ";
export const SET_PIX_WALLET_RANDOMKEY = "SET_PIX_WALLET_RANDOMKEY";

export const SET_CRYPTO_TRANSFERENCE = "SET_CRYPTO_TRANSFERENCE";
export const SET_FIAT_TRANSFERENCE = "SET_FIAT_TRANSFERENCE";
export const SET_PIX_TRANSFERENCE = "SET_PIX_TRANSFERENCE";
export const CLEAR_WALLET = "CLEAR_WALLET";
export const SET_ORIGIN_WALLET = "SET_ORIGIN_WALLET";
 
//CONTROL
export const SET_APP_VERSION = "SET_APP_VERSION";
export const SET_HAS_TASKS = "SET_HAS_TASKS";
export const UPDATE_TASKS_FEED = "UPDATE_TASKS_FEED";
export const UPDATED_TASKS_FEED = "UPDATED_TASKS_FEED";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATED_USER_DATA = "UPDATED_USER_DATA";
export const UPDATE_APP_FEED = "UPDATE_APP_FEED";
export const UPDATED_APP_FEED = "UPDATED_APP_FEED";

 