# Generated by Django 2.2 on 2021-11-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/clients', verbose_name='Foto do cliente')),
                ('firebase_uid', models.CharField(max_length=128, unique=True, verbose_name='Id do firebase')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('platform', models.CharField(blank=True, max_length=10, null=True, verbose_name='Plataforma')),
                ('balance', models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=50, null=True, verbose_name='Saldo atual')),
                ('points', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Pontos')),
                ('four_digits_pass', models.CharField(blank=True, max_length=250, null=True, verbose_name='Senha de 4 dígitos')),
                ('recommendation_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de indicação')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Usuário confirmou email?')),
                ('phone_confirmed', models.BooleanField(default=False, verbose_name='Usuário confirmou celular?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário ativo?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address', verbose_name='Endereço')),
                ('gender', models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Gender', verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Usuário do app',
                'verbose_name_plural': 'Usuários do app',
                'ordering': ['-created'],
                'unique_together': {('email', 'firebase_uid')},
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Currency', verbose_name='Moeda')),
                ('interest', models.ManyToManyField(blank=True, to='core.Interest', verbose_name='Interesses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='account.User', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência do Usuário',
                'verbose_name_plural': 'Preferências dos Usuários',
            },
        ),
    ]
