# Generated by Django 2.2 on 2021-11-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome')),
                ('streat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Número')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('complement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('uf', models.CharField(blank=True, max_length=3, null=True, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('latitude', models.CharField(blank=True, max_length=18, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=18, null=True, verbose_name='Longitude')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='País')),
                ('slug', models.SlugField(unique=True, verbose_name='Id do país')),
                ('lang_code', models.CharField(max_length=20, verbose_name='Código do idioma')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código da moeda')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/currencies', verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.CharField(max_length=10, unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interesses',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('APP', 'Aplicativo'), ('BUSINESS', 'For Business'), ('DASH', 'Dashboard admin')], max_length=20, verbose_name='Plataforma')),
                ('version', models.CharField(max_length=50, verbose_name='Versão')),
                ('released_at', models.DateField(verbose_name='Release feito em:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Configurações',
            },
        ),
    ]
