# Generated by Django 2.2 on 2021-11-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[('celo', 'Celo'), ('lovecrypto', 'LoveCrypto')], max_length=150, verbose_name='Identificador da carteira')),
                ('balance', models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=50, null=True, verbose_name='Balanço')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço da carteira')),
                ('secret', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chave privada')),
                ('words', models.CharField(blank=True, max_length=500, null=True, verbose_name='Palavras')),
                ('last_balance_update', models.DateTimeField(blank=True, null=True, verbose_name='Última atualização do saldo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='core.Currency', verbose_name='Moeda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='account.User', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
                'unique_together': {('user', 'identifier')},
            },
        ),
    ]
